FROM debian:jessie
#FROM resin/rpi-raspbian

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -y update && apt-get install -y supervisor git python python-pip python-shapely python-tz python-dev mongodb nginx wget busybox && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir /osmtracker
RUN pip install setuptools --no-use-wheel --upgrade
ADD requirements.txt /osmtracker/
RUN pip install -r /osmtracker/requirements.txt
